//
// Created by kisly on 04.08.2025.
//

#ifndef MODULES_HPP
#define MODULES_HPP

#define CORE_INCLUDE_VULKAN
#define CORE_INCLUDE_RENDERER_OPENGL_2D
#define CORE_INCLUDE_CONTEXT_LUA_SCRIPTS

#endif // MODULES_HPP
